### ISSUE TITLE
/account/balance endpoint not filtering for currency symbol

### ISSUE THREAD

**Issue by Kartiiyer12** [cardano-foundation/cardano-rosetta-java#259]
## Context & versions

When running '/account/balance', found that the 'currencies' field is not working, and whether I add this field or not, it will return all token balances.
If the currencies field is populated, only balances for the specified currencies need to be returned. If not populated, all available balances need to be returned.

## Steps to reproduce
Request body - 
{"network_identifier":{"blockchain":"cardano","network":"mainnet"},"account_identifier":{"address":"addr1zyq0kyrml023kwjk8zr86d5gaxrt5w8lxnah8r6m6s4jp4g3r6dxnzml343sx8jweqn4vn3fz2kj8kgu9czghx0jrsyqqktyhv"},"currencies":[{"symbol":"ADA","decimals":"6"}]}' 

## Actual behavior
Returning all the tokens for the address

## Expected behavior
Should return only the ADA value

**Comment by Drianna75** [comment]
Hi @Kammerlo, 

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Cardano Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!
